### ISSUE TITLE
persist generated ssh host key

### ISSUE THREAD

**Issue by pierreozoux** [tgbyte/docker-borg-backup#1]
Hi, and thanks for your beautiful image!

Do you know how to persist the host ssh key?

Thanks!

**Comment by dowdell** [comment]
You could try mounting a volume for `/home/borg/.ssh`

**Comment by netpro2k** [comment]
I know this is an old post, but in case anyone comes looking... What you actually want to do is mount a volume for `/etc/ssh/` as that is where the host keys are stored. The important contents of `/home/borg/.ssh` are already written out by the boot script.

**Comment by ginkel** [comment]
@pierreozoux Sorry, it took a while, but host key persistence is now implemented. Details in the README...
