### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pierreozoux** [tgbyte/docker-borg-backup#3]
I just realized I'm using your work, but you didn't put any license, could you correct that please?

Thanks!

**Comment by ginkel** [comment]
Thanks for bringing this up. Working on a solution, will end up being ALv2.

**Comment by pierreozoux** [comment]
Take a look at my fork, I added many features, If you still use it, it might be worth it for you ;)
I can now say I have a perfect solution for backing up docker-compose;) plus I have some grafana dashboards, If you are interested, let me know :) we could make a call and I show you around, and we could record it to share ;)

**Comment by ginkel** [comment]
Hi Pierre,

I'll get back to your offer next year. Can you point me to your fork? Can't seem to find it.

Thanks,
Thilo

**Comment by pierreozoux** [comment]
https://github.com/libresh/docker-borg

https://github.com/libresh/compose-borg-client/blob/master/README.md

And the server:
https://github.com/libresh/compose-borg-client/

I aslo developed a server that runs on kubernetes ;)
