### ISSUE TITLE
Debian 11?

### ISSUE THREAD

**Issue by rugk** [tgbyte/docker-borg-backup#5]
https://github.com/tgbyte/docker-borg-backup/blob/db934743aeb8c9ec87b968794a44ea613c0d93d0/Dockerfile#L1

[Debian 11 is out there](https://wiki.debian.org/DebianReleases), so maybe you should switch to that?

**Comment by ginkel** [comment]
Thanks for raising this issue. Prompted by the discussion in #6 I migrated the image to the most recent Ubuntu LTS due to their better track-record of shipping Docker images with security fixes included.
